language: go

go:
    - 1.6
    - tip

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/a85da9d6e9900584075a
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

before_install:
  - sudo apt-get install -y rpm
  - sudo apt-get install ruby-dev gcc make
  - gem install fpm
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/modocache/gover
  - go get github.com/golang/lint/golint
  - go get github.com/onsi/ginkgo/ginkgo
  - go get github.com/onsi/gomega
  - go get github.com/sohlich/elogrus
  - go get github.com/Sirupsen/logrus
  - go get gopkg.in/olivere/elastic.v3
  - go get github.com/cyberdelia/go-metrics-graphite
  - go get github.com/rcrowley/go-metrics
  - go get github.com/melnikk/go_jolokia
  - go get github.com/lytics/gowrapmx4j
  - go get github.com/gocql/gocql
  - go get github.com/docker/engine-api/client
  - go get github.com/docker/engine-api/types
  - go get golang.org/x/net/context
  - go get github.com/jessevdk/go-flags
  - go get github.com/gliderlabs/logspout
  - go get github.com/looplab/logspout-logstash
install:
  - make test
script:
  - make packages

before_deploy:
  - export RELEASE_PKG_TAR=$(ls build/cagrr*.tar.gz)
  - export RELEASE_PKG_RPM=$(ls build/cagrr*.rpm)
  - export RELEASE_PKG_DEB=$(ls build/cagrr*.deb)

deploy:
  provider: releases
  api_key:
    secure: brKcXZWaP5Gbl44RbvlD4kCGgpbqHUdavZ1h4NZF2mJwehh1TrHniHHtiM5DOpdS6Aa6v9YWvGaySIKqfi+U9icgbEDDf5FTlCDp5OhHCZh5xAGFCrHnoxq+j/ARBvd1412kvKQQZY/N7eFTUbC6TtxmO7DEqD5Zek/QhfgocXdO6nowkmMzPANwuxni3iV/zfDHZT2Buw217+NX/0KlKO0XPJRpAs6ebcAnsFnSaino7bje/n/2LyODk35gXXRM4vDGeZG2E1cwYh4dV8OaDdr9e75E2wqjDWFvTq1tj9hYAqCD3mI77LVwS8QqG2taTUP3Ez92ovS1oBu7khLbuzIXzvVs2D62xUsnvGFV+NtI8xoo/MQSl0Q/OUPkSlTzrw5XwVyzRttSsujqFsX6freqVLgODbjkIo9dFGCzLUOfAGeGFohtgSgaTxzY60sXhbAekCqSDZhpgOGmYaWDrQUlXbNdo3kuvw6X2LfRoA6FW2DaTu8XkiWinvUDeGWojaMz/zrHe+VYq1aI26bUR07t3emU75f0EZSZxyOkJQ3rGPdPdKsa1ndlYfR+odpS7M3T4Kam+p9Uo03mgwrhFkGI25PBpzFE2BGkBZG4ZQ2EzMq8DfsEvA45J/pmFuX1Lra87Znwn3+lPJo860JKJXvIyjJj1fxSsz1DnwbhNDQ=
  file:
    - "${RELEASE_PKG_TAR}"
    - "${RELEASE_PKG_RPM}"
    - "${RELEASE_PKG_DEB}"
  skip_cleanup: true
  on:
    tags: true
    condition: $TRAVIS_GO_VERSION = 1.6
